//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageDetectionProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSTUDENT
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string SURNAME { get; set; }
        public Nullable<int> NUMBER { get; set; }
        public string DEPARTMENT { get; set; }
        public string CELLPHONE { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<System.DateTime> ENTRANCE_DATE { get; set; }
        public string STATUS { get; set; }
    }
}
